# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pa02_development
  pool: 5
  username: gabem
  password: gabem
  host: localhost
  port: 3306



production:
    adapter: mysql2
    encoding: utf8
    database: pa03_production
    username: root
    password: copley66
    host: 96.126.113.242
    port: 3306

    
    